apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k8s-defus-co-tls
spec:
  secretName: k8s-defus-co
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: k8s.defus.co
  dnsNames:
    - k8s.defus.co
