name: Deploy MultiK8s
on:
  push:
    branches:
      - main

env:
  SHA: $(git rev-parse HEAD)

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: |-
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t matthewdefusco/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true matthewdefusco/react-test npm test

      # - name: Set Identity Provider
      #   uses: 'google-github-actions/auth@v0'
      #   with:
      #     workload_identity_provider: 'projects/483100437721/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
      #     service_account: 'gh-deployer@multi-338920.iam.gserviceaccount.com'

      # - name: Set Service Key
      #   uses: "google-github-actions/auth@v0"
      #   with:
      #     credentials_json: "${{ secrets.GKE_SA_KEY }}"

      - name: Set Identity Provider
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: "projects/35573725839/locations/global/workloadIdentityPools/github/providers/my-repo"
          service_account: "gh-deployer@multi-338920.iam.gserviceaccount.com"

      - name: Set Project
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: kubernetes-tutorial-452820

      - name: Auth
        run: |-
          gcloud --quiet auth configure-docker

      - name: Get Credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: multi-cluster
          location: us-central1-c
      # - name: Set Project
      #   uses: google-github-actions/setup-gcloud@v0
      #   with:
      #     project_id: kubernetes-tutorial-452820

      # - name: Auth
      #   run: |-
      #     gcloud --quiet auth configure-docker

      # - name: Get Credentials
      #   uses: google-github-actions/get-gke-credentials@v0
      #   with:
      #     cluster_name: multi-cluster
      #     location: us-central1-c

      - name: Build
        run: |-
          docker build -t matthewdefusco/multi-client:latest -t matthewdefusco/multi-client:${{ env.SHA }} -f ./client/Dockerfile ./client
          docker build -t matthewdefusco/multi-server:latest -t matthewdefusco/multi-server:${{ env.SHA }} -f ./server/Dockerfile ./server
          docker build -t matthewdefusco/multi-worker:latest -t matthewdefusco/multi-worker:${{ env.SHA }} -f ./worker/Dockerfile ./worker

      - name: Push
        run: |-
          docker push matthewdefusco/multi-client:latest
          docker push matthewdefusco/multi-server:latest
          docker push matthewdefusco/multi-worker:latest

          docker push matthewdefusco/multi-client:${{ env.SHA }}
          docker push matthewdefusco/multi-server:${{ env.SHA }}
          docker push matthewdefusco/multi-worker:${{ env.SHA }}

      - name: Apply
        run: |-
          kubectl apply -f k8s
          kubectl set image deployments/server-deployment server=matthewdefusco/multi-server:${{ env.SHA }}
          kubectl set image deployments/client-deployment client=matthewdefusco/multi-client:${{ env.SHA }}
          kubectl set image deployments/worker-deployment worker=matthewdefusco/multi-worker:${{ env.SHA }}
